export { Home } from './Home';
export { Login } from './login/Login';
export { Catches } from './catches/Catches';
export { Register } from './register/Register';
export { NotFound } from './NotFound';
export { MyAccount } from './myAccount/MyAccount';
export { Questions } from './questions/Questions';
export { QuestionDetails } from './questionDetails/QuestionDetails';
export { UserDetails } from './userDetails/UserDetails';
