export { Home } from './Home';
export { Login } from './Login';
export { Catches } from './Catches';
export { Register } from './Register';
export { NotFound } from './NotFound';
export { MyAccount } from './MyAccount';
export { Questions } from './Questions';
export { Events } from './Events';
export { QuestionDetails } from './details/QuestionDetails';
