name: Ensure Tacklebox Schemas Version

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-tacklebox-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Get latest tacklebox-schemas version
        id: latest
        run: |
          LATEST=$(npm view tacklebox-schemas version)
          echo "latest_version=$LATEST" >> $GITHUB_ENV

      - name: Check tacklebox-schemas version
        env:
          LATEST_VERSION: ${{ env.latest_version }}
        run: |
          # Get actual installed version
          INSTALLED=$(npm list tacklebox-schemas --depth=0 --json | jq -r '.dependencies["tacklebox-schemas"].version')

          echo "Installed version: $INSTALLED"
          echo "Latest version: $LATEST_VERSION"

          if [ "$INSTALLED" != "$LATEST_VERSION" ]; then
            echo "tacklebox-schemas version mismatch. Expected $LATEST_VERSION, found $INSTALLED"
            echo "Run: npm install tacklebox-schemas@latest"
            exit 1
          else
            echo "tacklebox-schemas version is up-to-date"
          fi
